# Generated by Django 5.2.1 on 2025-05-12 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pergunta')),
                ('category', models.CharField(choices=[('BASICA', 'Estatística Básica'), ('TENDENCIA', 'Tendência Central'), ('PROBABILIDADE', 'Probabilidade'), ('GRAFICA', 'Análise Gráfica'), ('CORRELACAO', 'Correlação')], max_length=20)),
                ('posicao_tabuleiro', models.PositiveIntegerField(help_text='Número da casa do tabuleiro associada a esta pergunta', verbose_name='Casa do Tabuleiro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_tempo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_tempo', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='IN_PROGRESS', max_length=20)),
                ('ganhador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_ganhos', to=settings.AUTH_USER_MODEL)),
                ('partidas', models.ManyToManyField(related_name='jogos_partidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos_jogados', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('pontuacao_media', models.FloatField(default=0.0)),
                ('user_jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['jogos_jogados'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Resposta')),
                ('e_correto', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_jogo', to='core.game')),
            ],
            options={
                'unique_together': {('jogo', 'jogador')},
            },
        ),
    ]
