# Generated by Django 5.2.1 on 2025-05-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jogador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['posicao_tabuleiro', 'category'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='dica',
            field=models.TextField(blank=True, help_text='Dica opcional que pode ser mostrada ao jogador (com penalidade de pontos)', null=True, verbose_name='Dica'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='explicacao',
            field=models.TextField(blank=True, help_text='Explicação detalhada da resposta para mostrar após o jogador responder', null=True, verbose_name='Explicação'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem opcional para ilustrar a pergunta', null=True, upload_to='perguntas/'),
        ),
    ]
