# Generated by Django 5.2.1 on 2025-05-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pergunta_options_pergunta_dica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='codigo',
            field=models.CharField(default='0000', max_length=4, unique=True, verbose_name='Código Pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='codigo',
            field=models.CharField(default='0000', max_length=4, unique=True, verbose_name='Código Resposta'),
        ),
    ]
