# Generated by Django 5.2.1 on 2025-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pergunta_codigo_resposta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='codigo',
            field=models.CharField(default='0000', max_length=4, verbose_name='Código Resposta'),
        ),
    ]
