# Generated by Django 5.2.1 on 2025-05-18 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resposta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='codigo',
            field=models.CharField(default='0000', help_text='Código único no formato P000 (ex: P001, P002)', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_codigo', message='O código deve estar no formato P seguido de 3 números (ex: P001)', regex='^P\\d{3}$')], verbose_name='Código Pergunta'),
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('codigo', 'pergunta')},
        ),
    ]
