# Generated by Django 5.2.1 on 2025-05-18 22:34

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pergunta_codigo_alter_resposta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Imagem opcional para ilustrar a pergunta', null=True, upload_to='perguntas/'),
        ),
    ]
