# Generated by Django 5.2.1 on 2025-05-18 22:53

import core.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pergunta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Imagem opcional para ilustrar a pergunta', null=True, upload_to='perguntas/', validators=[core.models.validate_image]),
        ),
    ]
