# Generated by Django 5.2.1 on 2025-05-19 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pergunta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='codigo',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_codigo', message='O código deve estar no formato R seguido de 5 números (ex: R00101)', regex='^R\\d{3}\\d{2}$')], verbose_name='Código Resposta'),
        ),
    ]
