# Generated by Django 5.2.1 on 2025-05-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resposta_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='maior_pontuacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='tempo_medio_jogo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='total_perguntas_certas',
            field=models.IntegerField(default=0),
        ),
    ]
