# Generated by Django 5.2.1 on 2025-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jogador_maior_pontuacao_jogador_tempo_medio_jogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='category',
            field=models.CharField(choices=[('BASICA', 'Estatística Básica'), ('TENDENCIA', 'Tendência Central'), ('PROBABILIDADE', 'Probabilidade'), ('GRAFICA', 'Análise Gráfica'), ('CORRELACAO', 'Correlação'), ('DISPERSAO', 'Dispersão')], max_length=20),
        ),
    ]
